# Feature Engineering

## Transforming Data
- apply()
- map()
- assign()
- replace (old, new)
- rename (columns{old,new})
- sort_value()
- sort_index()
- reset_index()
- rank()
- Reorder columns

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")

In [3]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
df2 = df.copy()

In [5]:
df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 50000 else "10%") #.appply() -> high order function

In [6]:
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [7]:
gender_map = {"Male" : "M", "Female" : "F", "Unknown" : "U"}
df2["gender"] = df2["gender"].map(gender_map)

In [8]:
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  20%
1    1      John Doe  29.0     USA      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%

In [9]:
# assign
df2.assign(new_income = df2["income"]* 1.10)

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%     63800.0

In [ ]:
df2["country"] = df2["country"].replace("USA","United State")

In [ ]:
df2

In [ ]:
df

In [ ]:
df2

In [ ]:
# rename
df2.columns = ["Id","Name","Age","Country","Gender","Income","Tax"]

In [ ]:
df2

In [ ]:
df2.rename(columns={"Income":"Salary"})
# change row label
df2.rename(index = {1:"First"})

In [ ]:
# sort
sorted_df = df2.sort_values("Income")
#df2.sort_values("Income",ascending= False)
sorted_df.sort_index()

#reset
sorted_df.reset_index()
sorted_df.reset_index(drop = True) #do not preserve original index

#ranking
sorted_df["Rabking"] = sorted_df["Income"].rank()
sorted_df

In [ ]:
df2

In [ ]:
new_col = df2[["Name","Age","Country","Gender","Income","Tax","Id"]]

In [ ]:
new_col

## How to write in csv

In [ ]:
df2 = df2.drop_duplicates()
df2 = df2.fillna(0)

df2 = df2.sort_values("Income")

df2 = df2.reset_index(drop = True)

df2.to_csv("sorted_data.csv")

In [ ]:
df2.fillna(0)

## Grouping and Aggregate of Data
- groupby()
- mean/sum/max/min/count
- agg()

In [ ]:
df.groupby("country")["income"].mean()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()

df.groupby("gender")["income"].mean()

df.groupby("country")["income"].agg(avg_salary = "mean",min_salary = "min",max_salary= "max",count= "count")

## Melt & Pivot

- Melt - wide to long format <br>
melt(id_vars #want to keep, value_vars #want unpivot, var_name #new_col name, value_name #new_col value)

- Pivot - long to wide format
pivot(index #keep, coulmns,values)

In [ ]:
df = pd.DataFrame({
    "country" : ["USA","USA","India","Pakistan"],
    "year" : [2020,2021,2020,2021],
    "sales" : [100,120,90,130],
    "profit" : [20,30,18,22],
    "tax" : [10,20,30,40]
})

In [ ]:
melted_df = df.melt(
    id_vars = ["country","year"],
    value_vars = ["sales","profit","tax"],
    var_name = "matrics",
    value_name = "value"
)

In [ ]:
melted_df

In [ ]:
original = melted_df.pivot(
    index = ["country","year"],
    columns= "matrics",
    values="value"
)

In [ ]:
original

## Merge and Join
- inner join
- left join 
- right join
- outer join

In [ ]:
df_customer = pd.DataFrame(
    {
        "customer_id" : [1,2,3,4],
        "name" : ["Adam","Bob","Charlie","Dave"]
    }
)

df_orders = pd.DataFrame({
    "order_id" : [101,102,103,104],
    "customer_id" : [2,1,4,5],
    "amount" : [250, 120, 300, 180]
})

In [ ]:
df_customer

In [ ]:
df_orders

In [ ]:
#inner join
pd.merge(df_customer,df_orders, on = "customer_id")

In [ ]:
#left join
pd.merge(df_customer,df_orders, on = "customer_id",how = "left")

In [ ]:
#right join
pd.merge(df_customer,df_orders, on = "customer_id",how = "right")

In [ ]:
#outer join
pd.merge(df_customer,df_orders, on = "customer_id",how = "outer")

## Data concatenation
- Stacking DataFrame on the top of each other (rows) and side by side (columns)

In [ ]:
df1 = pd.DataFrame(
    {
        "id" : [1,2,3],
        "name" : ["Adam","Bob","Dave"]
    }
)

df2 = pd.DataFrame(
    {
        "id" : [4,5,6],
        "name" : ["Eve","Fester","Charlie"]
    }
)

In [ ]:
df1

In [ ]:
df2

In [ ]:
pd.concat([df1,df2])

In [ ]:
pd.concat([df1,df2],ignore_index=True)

In [ ]:
pd.concat([df1,df2],axis=1)