# Pandas Assignment Problems
Practical Exploration & Analysis

**Instructions:** Solve each question in the empty code cell below it.

## Q1 — IRIS Dataset
**Dataset:** [Iris Flower Dataset](https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv)

Start by loading the dataset.

In [6]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load (usually "IRIS.csv" for this dataset)
file_path = "IRIS.csv"

# Load the latest version
df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "arshid/iris-flower-dataset",
    file_path,
)

print("First 5 records:")
print(df.head())

/var/folders/d5/tdr60cjn3091k4tbstb__v5r0000gn/T/ipykernel_6232/2672787804.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to /Users/malikqousainraza/.cache/kagglehub/datasets/arshid/iris-flower-dataset/versions/1/IRIS.csv...

100%|██████████| 4.51k/4.51k [00:00<00:00, 3.71MB/s]

First 5 records:
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### A. Display the following information
- First 10 rows
- Shape and data types
- Summary statistics: mean, standard deviation, minimum, maximum

In [9]:
print("first 10 row: \n",df.head(10))

first 10 row:
    sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [10]:
df.shape

(150, 5)

In [11]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

### B. Filter the rows
- `petal_length > 4.5`
- `species == "Iris-virginica"`

In [15]:
df[df["sepal_length"] > 4.5]

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[145 rows x 5 columns]

In [21]:
df[df["species"] == "Iris-virgincia"]

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []

### C. Group by `species` and compute
- Average `sepal_length`
- Maximum `petal_width`
- Standard deviation of `sepal_width`

In [ ]:
df.groupby()

### D. Create a new column
- `petal_ratio = petal_length / petal_width`
- Find the average `petal_ratio` for each species.

## Q2 — TITANIC Dataset
**Dataset:** [Titanic Dataset](https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv)

Start by loading the dataset.

### A. Display only these columns
- `Name`
- `Sex`
- `Age`
- `Fare`
- `Survived`

### B. Filter passengers who
- Are female
- Have `Fare > 30`

### C. Group by `Pclass` and compute
- Survival rate
- Average fare
- Average age