# Pandas Assignment Problems
Practical Exploration & Analysis

**Instructions:** Solve each question in the empty code cell below it.

## Q1 — IRIS Dataset
**Dataset:** [Iris Flower Dataset](https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv)

Start by loading the dataset.

In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load (usually "IRIS.csv" for this dataset)
file_path = "IRIS.csv"

# Load the latest version
df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "arshid/iris-flower-dataset",
    file_path,
)

print("First 5 records:")
print(df.head())

/opt/anaconda3/envs/venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/var/folders/d5/tdr60cjn3091k4tbstb__v5r0000gn/T/ipykernel_6997/2672787804.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

First 5 records:
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### A. Display the following information
- First 10 rows
- Shape and data types
- Summary statistics: mean, standard deviation, minimum, maximum

In [3]:
print("first 10 row: \n",df.head(10))

first 10 row:
    sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [4]:
df.shape

(150, 5)

In [5]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

### B. Filter the rows
- `petal_length > 4.5`
- `species == "Iris-virginica"`

In [6]:
df[df["sepal_length"] > 4.5]

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[145 rows x 5 columns]

In [7]:
df[df["species"] == "Iris-virgincia"]

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []

### C. Group by `species` and compute
- Average `sepal_length`
- Maximum `petal_width`
- Standard deviation of `sepal_width`

In [18]:
df.groupby("species")["sepal_length"].mean()

species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: sepal_length, dtype: float64

In [ ]:
df.groupby("species")["petal_width"].max()

species
Iris-setosa        0.6
Iris-versicolor    1.8
Iris-virginica     2.5
Name: petal_width, dtype: float64

In [23]:
print("standard davaition\n", df.groupby("species")["petal_width"].std())

standard davaition
 species
Iris-setosa        0.107210
Iris-versicolor    0.197753
Iris-virginica     0.274650
Name: petal_width, dtype: float64

### D. Create a new column
- `petal_ratio = petal_length / petal_width`
- Find the average `petal_ratio` for each species.

In [25]:
df2 = df.copy()

In [31]:
df2.sample(5)

     sepal_length  sepal_width  petal_length  petal_width          species
60            5.0          2.0           3.5          1.0  Iris-versicolor
48            5.3          3.7           1.5          0.2      Iris-setosa
136           6.3          3.4           5.6          2.4   Iris-virginica
91            6.1          3.0           4.6          1.4  Iris-versicolor
46            5.1          3.8           1.6          0.2      Iris-setosa

In [36]:
df2 = df2.assign(petal_ratio = df2["petal_length"] / df2["petal_width"])

In [37]:
df2["petal_ratio"]

0      7.000000
1      7.000000
2      6.500000
3      7.500000
4      7.000000
         ...
145    2.260870
146    2.631579
147    2.600000
148    2.347826
149    2.833333
Name: petal_ratio, Length: 150, dtype: float64

In [39]:
df2.groupby("species")["petal_ratio"].mean()

species
Iris-setosa        7.078000
Iris-versicolor    3.242837
Iris-virginica     2.780662
Name: petal_ratio, dtype: float64

## Q2 — TITANIC Dataset
**Dataset:** [Titanic Dataset](https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv)

Start by loading the dataset.

In [40]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "Titanic-Dataset.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "yasserh/titanic-dataset",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/var/folders/d5/tdr60cjn3091k4tbstb__v5r0000gn/T/ipykernel_6997/1732105544.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to /Users/malikqousainraza/.cache/kagglehub/datasets/yasserh/titanic-dataset/versions/1/Titanic-Dataset.csv...

100%|██████████| 59.8k/59.8k [00:00<00:00, 238kB/s]

First 5 records:    PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [41]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### A. Display only these columns
- `Name`
- `Sex`
- `Age`
- `Fare`
- `Survived`

In [43]:
df[["Name","Sex","Age","Fare","Survived"]]

,Name,Sex,Age,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,7.2500,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
2,"Heikkinen, Miss. Laina",female,26.0,7.9250,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
4,"Allen, Mr. William Henry",male,35.0,8.0500,0
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,13.0000,0
887,"Graham, Miss. Margaret Edith",female,19.0,30.0000,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,23.4500,0
889,"Behr, Mr. Karl Howell",male,26.0,30.0000,1
890,"Dooley, Mr. Patrick",male,32.0,7.7500,0

### B. Filter passengers who
- Are female
- Have `Fare > 30`

In [51]:
P = df[(df["Sex"] == "female") & (df["Fare"] > 30)]

In [52]:
P[["Sex","Fare"]]

        Sex      Fare
1    female   71.2833
3    female   53.1000
9    female   30.0708
25   female   31.3875
31   female  146.5208
..      ...       ...
853  female   39.4000
856  female  164.8667
863  female   69.5500
871  female   52.5542
879  female   83.1583

[113 rows x 2 columns]

### C. Group by `Pclass` and compute
- Survival rate
- Average fare
- Average age

In [56]:
(df.groupby('Pclass')['Survived'].mean() * 100).round(2)

Pclass
1    62.96
2    47.28
3    24.24
Name: Survived, dtype: float64

In [57]:
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [58]:
df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64